<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Emmett Henry">
<meta name="dcterms.date" content="2026-05-18">

<title>Analysis of Property Prices East and West of Alter Rd, Detroit MI</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Alter_Rd_Analysis - Copy_files/libs/clipboard/clipboard.min.js"></script>
<script src="Alter_Rd_Analysis - Copy_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Alter_Rd_Analysis - Copy_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Alter_Rd_Analysis - Copy_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Alter_Rd_Analysis - Copy_files/libs/quarto-html/popper.min.js"></script>
<script src="Alter_Rd_Analysis - Copy_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Alter_Rd_Analysis - Copy_files/libs/quarto-html/anchor.min.js"></script>
<link href="Alter_Rd_Analysis - Copy_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Alter_Rd_Analysis - Copy_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Alter_Rd_Analysis - Copy_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Alter_Rd_Analysis - Copy_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Alter_Rd_Analysis - Copy_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#data-and-libraries" id="toc-data-and-libraries" class="nav-link active" data-scroll-target="#data-and-libraries">Data and libraries</a></li>
  <li><a href="#data-cleaning" id="toc-data-cleaning" class="nav-link" data-scroll-target="#data-cleaning">Data Cleaning</a></li>
  <li><a href="#welchs-two-sample-t-test" id="toc-welchs-two-sample-t-test" class="nav-link" data-scroll-target="#welchs-two-sample-t-test">Welch’s Two-Sample T-test:</a></li>
  <li><a href="#non-parametric-test-mann-whitney-wilcoxon-test" id="toc-non-parametric-test-mann-whitney-wilcoxon-test" class="nav-link" data-scroll-target="#non-parametric-test-mann-whitney-wilcoxon-test">Non-Parametric Test: Mann-Whitney-Wilcoxon Test</a></li>
  <li><a href="#t-test-example" id="toc-t-test-example" class="nav-link" data-scroll-target="#t-test-example">T-Test Example</a></li>
  <li><a href="#conclusion-and-discussion" id="toc-conclusion-and-discussion" class="nav-link" data-scroll-target="#conclusion-and-discussion">Conclusion and Discussion</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Analysis of Property Prices East and West of Alter Rd, Detroit MI</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Emmett Henry </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">May 18, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="data-and-libraries" class="level3">
<h3 class="anchored" data-anchor-id="data-and-libraries">Data and libraries</h3>
<p>The parcels dataset used in this analysis was generated using 30 random parcels selected from each side of a 1 km buffer around Fox Creek in QGIS. Original parcel boundary data was acquired from Wayne County GIS data’s Parcels dataset at https://www.waynecountymi.gov/Government/Departments/Information-Technology/Maps-Data/GIS-Data. Home prices were then determined by searching Zillow and recording the current Zillow price as of 5/12/2026. The original dataset was created in Google Sheets, then exported as a CSV file for analysis.</p>
<p>The readr library is used to convert the currency formatting of Google Sheets into standard numeric format.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>parcels <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"Jefferson_Chalmers_Home_Prices.csv"</span>)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Example data rows are shown below. The first four columns identify the parcel in question by street, city, state, and zip code. `Zillow.Price` is the recorded Zillow price as of 5/12/2026. `(Not on Zillow)` refers to a property that had no information on Zillow or could not be located in Zillow’s records. `“Unknown”` or `“Price Unknown”` are quotes directly from Zillow. `Price.Date` is the date that the Zillow data was accessed. `Zillow.Property.Type` is the property type listed on Zillow, with `(Not on Zillow)` used as a placeholder for properties that could not be found on the site. `E.W.of.Alter.Rd` refers to a property’s position either East of West of Alter Rd along Fox Creek. `Notes.` refers to any additional insight on the property that could be gained through images on Zillow, then through Google Maps imagery and street view if no Zillow image was present. Notes are not official data and represent the author’s best guess as to the property’s function, and thus have not been included in this analysis.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(parcels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           propstreet propcity propstate propzip    Zillow.Price Price.Date
1 14640 HARBOR ISLAND  DETROIT        MI   48215 (Not on Zillow)  5/12/2026
2         276 ASHLAND  DETROIT        MI   48215 (Not on Zillow)  5/12/2026
3      937 MANISTIQUE  DETROIT        MI   48215 (Not on Zillow)  5/12/2026
4      870 MANISTIQUE  DETROIT        MI   48215       "Unknown"  5/12/2026
5          334 PHILIP  DETROIT        MI   48215 "Price Unknown"  5/12/2026
6         878 ASHLAND  DETROIT        MI   48215     $262,500.00  5/12/2026
  Zillow.Property.Type E.W.of.Alter.Rd
1      (Not on Zillow)            West
2      (Not on Zillow)            West
3      (Not on Zillow)            West
4              Unknown            West
5              Unknown            West
6        Single Family            West
                                              Notes.
1 Could not identify via both Zillow and Google Maps
2                                        Boat House?
3                "Original Primitive Baptist Church"
4                                        Vacant Lot?
5                                         Vacant Lot
6                                                   </code></pre>
</div>
</div>
</section>
<section id="data-cleaning" class="level3">
<h3 class="anchored" data-anchor-id="data-cleaning">Data Cleaning</h3>
<p>A new column `Zillow.Numeric` is created with converted numeric price data stripped of dollar signs and commas. Non-numeric values are changed to `NA`. This allows for easy analysis of home prices.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>parcels<span class="sc">$</span>Zillow.Numeric <span class="ot">&lt;-</span> <span class="fu">parse_number</span>(parcels<span class="sc">$</span>Zillow.Price)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: 6 parsing failures.
row col expected          actual
  1  -- a number (Not on Zillow)
  2  -- a number (Not on Zillow)
  3  -- a number (Not on Zillow)
  4  -- a number "Unknown"      
  5  -- a number "Price Unknown"
... ... ........ ...............
See problems(...) for more details.</code></pre>
</div>
</div>
<p>The first few rows of the dataset with the new column are shown below:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(parcels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>           propstreet propcity propstate propzip    Zillow.Price Price.Date
1 14640 HARBOR ISLAND  DETROIT        MI   48215 (Not on Zillow)  5/12/2026
2         276 ASHLAND  DETROIT        MI   48215 (Not on Zillow)  5/12/2026
3      937 MANISTIQUE  DETROIT        MI   48215 (Not on Zillow)  5/12/2026
4      870 MANISTIQUE  DETROIT        MI   48215       "Unknown"  5/12/2026
5          334 PHILIP  DETROIT        MI   48215 "Price Unknown"  5/12/2026
6         878 ASHLAND  DETROIT        MI   48215     $262,500.00  5/12/2026
  Zillow.Property.Type E.W.of.Alter.Rd
1      (Not on Zillow)            West
2      (Not on Zillow)            West
3      (Not on Zillow)            West
4              Unknown            West
5              Unknown            West
6        Single Family            West
                                              Notes. Zillow.Numeric
1 Could not identify via both Zillow and Google Maps             NA
2                                        Boat House?             NA
3                "Original Primitive Baptist Church"             NA
4                                        Vacant Lot?             NA
5                                         Vacant Lot             NA
6                                                            262500</code></pre>
</div>
</div>
</section>
<section id="welchs-two-sample-t-test" class="level3">
<h3 class="anchored" data-anchor-id="welchs-two-sample-t-test">Welch’s Two-Sample T-test:</h3>
<p>A common tool for comparing means of two groups is the T-Test. R defaults to Welch’s T-Test for two-sample t-tests, which allows for smaller sample sizes. Before we can use this test, we must check that its assumptions are met, including independence of observatios, a continuous dependent variable, and normal distribution of the populations to be analyzed.</p>
<p>Independence of Observations: True, populations were chosen by a random selection operation in QGIS.</p>
<p>Continuous Dependent Variable: True, variable is in dollars.</p>
<p>Normality: validate using the Shapiro-Wilk Normality test for each population. The first population is parcels East of Alter Rd, which is extracted by a subset operation, and the other population is parcels West of Alter Rd, which is again extracted using a subset operation. shapiro.test is then applied to the Zillow.Numeric values of each of the these subsets.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>east_parcels <span class="ot">&lt;-</span> <span class="fu">subset</span>(parcels, parcels<span class="sc">$</span>E.W.of.Alter.Rd <span class="sc">==</span> <span class="st">"East"</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>west_parcels <span class="ot">&lt;-</span> <span class="fu">subset</span>(parcels, parcels<span class="sc">$</span>E.W.of.Alter.Rd <span class="sc">==</span> <span class="st">"West"</span>)</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(east_parcels<span class="sc">$</span>Zillow.Numeric)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  east_parcels$Zillow.Numeric
W = 0.98594, p-value = 0.9567</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(west_parcels<span class="sc">$</span>Zillow.Numeric)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  west_parcels$Zillow.Numeric
W = 0.64354, p-value = 1.383e-06</code></pre>
</div>
</div>
<p>The p-value of the East Parcels population is 0.9567, which falls above the standard alpha value of 0.05. Thus, we do not reject the null hypothesis that the data is non-normally distributed, and conclude that the East population’s price data meets the normality assumption for the T-Test. The p-value for the West poopulation is 1.383e-06, which falls below the standard alpha value of 0.05. Thus, we reject the null hypothesis that the West population’s price data is normally distributed, and conclude that it <strong>fails</strong> to meet this assumption for the T-Test.</p>
<p>To understand why the West parcels failed this assumption, histograms showing the east and west parcels’ price distributions are shown below. The East histogram shows a fairly standard bell shape, while the West histogram has a strong right skew.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(east_parcels<span class="sc">$</span>Zillow.Numeric)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Alter_Rd_Analysis---Copy_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(west_parcels<span class="sc">$</span>Zillow.Numeric)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Alter_Rd_Analysis---Copy_files/figure-html/unnamed-chunk-6-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>One potential fix for right-skewed data is to take the log of the dataset. A histogram of the log of West parcel prices is shown below. Although it is less right-skewed than before, it still does not show an ideal bell-curve shape.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>log_west <span class="ot">&lt;-</span> <span class="fu">log</span>(west_parcels<span class="sc">$</span>Zillow.Numeric)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(log_west)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Alter_Rd_Analysis---Copy_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>To confirm whether this logged data would meet the t-test requirement, a Shapiro-Wilk normality test is applied to it. As we can see below, the resulting p-value of 0.0006687 still falls below the standard alpha value of 0.05, leading us to once again reject the null hypothesis that the data is normally distributed. Thus, taking the log of the parcel price data does not fix the non-normality issue, and it still <strong>fails</strong> the Shapiro-Wilk test for normality.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(log_west)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  log_west
W = 0.82715, p-value = 0.0006687</code></pre>
</div>
</div>
</section>
<section id="non-parametric-test-mann-whitney-wilcoxon-test" class="level3">
<h3 class="anchored" data-anchor-id="non-parametric-test-mann-whitney-wilcoxon-test">Non-Parametric Test: Mann-Whitney-Wilcoxon Test</h3>
<p>The Mann-Whitney-Wilcoxon Test is an alternative to the T-Test that accounts for non-normal distributions of populations, thus resolving the issue of non-normality in the West parcel price data. Results comparing East and West parcel price data are seen below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">wilcox.test</span>(Zillow.Numeric <span class="sc">~</span> E.W.of.Alter.Rd, <span class="at">data =</span> parcels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in wilcox.test.default(x = DATA[[1L]], y = DATA[[2L]], ...): cannot
compute exact p-value with ties</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Wilcoxon rank sum test with continuity correction

data:  Zillow.Numeric by E.W.of.Alter.Rd
W = 719, p-value = 6.516e-10
alternative hypothesis: true location shift is not equal to 0</code></pre>
</div>
</div>
<p>Given the resulting p-value of 6.516e-10, we reject the null hypothesis that the true difference in means is equal to 0. Thus, we can conclude there is a significant difference between the Zillow home prices for the East and West side of Alter Rd. However, this test does not provide estimated means for either group, or show the estimated difference between the two.</p>
</section>
<section id="t-test-example" class="level3">
<h3 class="anchored" data-anchor-id="t-test-example">T-Test Example</h3>
<p>Although the assumptions for this test are not fully met, a T-Test gives estimated means for the different populations. While we cannot be completely confident in these results due to the non-normality in the West data, a T-Test for the East and West parcel data is presented below.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(Zillow.Numeric <span class="sc">~</span> E.W.of.Alter.Rd, <span class="at">data =</span> parcels)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  Zillow.Numeric by E.W.of.Alter.Rd
t = 12.409, df = 43.361, p-value = 7.311e-16
alternative hypothesis: true difference in means between group East and group West is not equal to 0
95 percent confidence interval:
 379608.2 526901.5
sample estimates:
mean in group East mean in group West 
         507241.38           53986.56 </code></pre>
</div>
</div>
<p>The resulting p-value of 7.311e-16 falls below the 0.05 alpha value, concurring with the Mann-Whitney-Wilcoxon test results. The mean of East parcels given is $507,241.38, and is roughly ten times larger than the West parcels’ mean of $53,986.56. Thus, while this test is not entirely reliable, there is a large difference between estimated means, and we can likely assume the East parcels have a much higher average value than the west parcels.</p>
</section>
<section id="conclusion-and-discussion" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-and-discussion">Conclusion and Discussion</h3>
<p>Given the results of the Mann-Whitney-Wilcoxon non-parametric test, we conclude that there is a significant difference between parcel prices on the East and West sides of Alter Rd in Detroit, MI. A preliminary T-Test, while not necessarily reliable, suggests that the East parcel prices are, on average, roughly 10 times greater than West parcel prices.</p>
<p>Further investigation could be useful in multiple areas. For one, several parcels were omitted from this analysis due to lacking information on Zillow. A more comprehensive dataset might yield additional insights. Furthermore, an analysis of property types could highlight reasons for the differences seen in this analysis. A brief skim of the dataset itself shows relatively homogenous parcel types for the East side, but hgihly mixed parcel uses for the West side. Finally, the Alter Rd boundary nearly coincides with the border between the cities of Detroit and Grosse Point Woods. Determining to what extend these differences in property prices are caused by the canal versus the city boundary would be an ideal next step for research.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>